### ISSUE TITLE
Collision files unable to be parsed

### ISSUE THREAD

**Issue by colinthomas5** [ProfElements/cftkk#1]
Collision files spanning across numerous different .gcp files were unable to be parced. Some files errored out immediately while others got as far as "TRIANGLES OKAY" before erroring out.
[collisions_cftkk.zip](https://github.com/ProfElements/cftkk/files/11327426/collisions_cftkk.zip)

**Comment by ProfElements** [comment]
fixed with latest push (check discord for updated binary
